package com.driveease.rental.model;

import jakarta.persistence.*;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDateTime;

/**
 * The BookingRequest entity represents an initial inquiry made by a customer.
 * Unlike a finalized 'Booking', this record stays in a 'PENDING' state
 * until an authorized agent reviews and approves it.
 */
@Entity
@Table(name = "booking_request")
@Data // Lombok annotation to automatically generate getters, setters, and other utility methods
public class BookingRequest {

    /**
     * Primary Key: Unique ID for each booking inquiry.
     * Automatically generated by the database using an identity column.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long requestId;

    /**
     * Relationship to the Customer who initiated the request.
     * Maps to the 'customer_id' column in the database.
     */
    @ManyToOne
    @JoinColumn(name = "customer_id")
    private User customer;

    /**
     * Relationship to the specific Support Agent assigned to handle this request.
     * Each request is routed to a selected agent for approval.
     */
    @ManyToOne
    @JoinColumn(name = "agent_id")
    private User agent;

    /**
     * Link to the specific Vehicle Contract (the car listing) being requested.
     */
    @ManyToOne
    @JoinColumn(name = "contract_id")
    private VehicleContract vehicleContract;

    /**
     * Redundant storage of vehicle type for quick display without needing complex joins.
     */
    private String vehicleType;

    /**
     * The total calculated price for the requested rental period.
     */
    private BigDecimal finalPrice;

    /**
     * The lifecycle status of the request.
     * Defaults to "PENDING" upon creation.
     */
    private String status = "PENDING";

    /**
     * Records the exact date and time the request was submitted.
     * Initialized to current system time by default.
     */
    private LocalDateTime requestDate = LocalDateTime.now();
}