package com.driveease.rental.repository;

import com.driveease.rental.model.Booking;
import com.driveease.rental.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.stereotype.Repository;
import java.math.BigDecimal;
import java.util.List;

/**
 * BookingRepository acts as the Data Access Object (DAO) for the Booking Entity.
 * It provides built-in JPA methods and custom SQL/JPQL queries to retrieve
 * transaction-related data from the database.
 */
@Repository
public interface BookingRepository extends JpaRepository<Booking, Long> {

    /**
     * Standard JPA query to find all bookings assigned to a specific User object (Agent).
     */
    List<Booking> findByAgent(User agent);

    /**
     * Standard JPA query to find all bookings associated with a specific User object (Customer).
     */
    List<Booking> findByCustomer(User customer);

    /**
     * Specialized Filter: Retrieves all bookings based on the Agent's unique User ID.
     * This allows the system to filter the agent's confirmed transactions directly.
     */
    List<Booking> findByAgentUserId(Long agentId);

    // ========================================================================
    // ANALYTICS & REPORTING QUERIES (Used for Admin Dashboard)
    // ========================================================================

    /**
     * Calculates the total revenue generated by the system.
     * It sums up the 'finalPrice' column from every record in the booking table.
     * @return Total revenue as a BigDecimal for high precision.
     */
    @Query("SELECT SUM(b.finalPrice) FROM Booking b")
    BigDecimal getTotalRevenue();

    /**
     * Counts the total number of successful bookings processed in the system.
     * This is used for high-level statistics in the Admin portal.
     * @return Total count of booking records.
     */
    @Query("SELECT COUNT(b) FROM Booking b")
    Long getTotalBookingCount();
}